import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { ArrowLeft, ArrowUpRight, CalendarDays, Clock, MapPin, Users, Download } from 'lucide-react';
import { Header, Footer } from '@/components/site';
import { events } from '@/lib/content';
import { base } from '@/lib/base';
export function generateStaticParams(){return events.map(e=>({id:e.id}))}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const event=events.find(e=>e.id===id);return {title:event?.title??'Event not found',description:event?.summary,openGraph:{title:event?.title,description:event?.summary,images:[]},twitter:{card:'summary',title:event?.title,description:event?.summary,images:[]}}}
export default async function EventDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const event=events.find(e=>e.id===id);if(!event)notFound();const date=new Date(`${event.date}T12:00:00Z`).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Berlin'});return <><Header/><main id="main" className="wrap detail-page"><Link className="text-link back-link" href="/calendar"><ArrowLeft size={17}/> All events</Link><div className="detail-grid"><article><div className="detail-labels"><span className="tag">{event.category}</span><span className="eyebrow">{event.format}</span></div><h1>{event.title}</h1><p className="detail-lead">{event.summary}</p><div className="detail-body"><h2>What to know before you go</h2><p>This event is organized by {event.group}. The full announcement contains the latest information and any registration instructions.</p>{event.addressNote&&<div className="notice"><MapPin size={20}/><p>{event.addressNote}</p></div>}<dl className="practical-list"><div><dt>Language & preparation</dt><dd>Check the organizer’s announcement, or ask the host what to expect.</dd></div><div><dt>Cost & registration</dt><dd>Follow the original listing for any costs, capacity limits, and RSVP requirements.</dd></div><div><dt>Access & arrival</dt><dd>Contact the host if you need venue accessibility information or help finding the group.</dd></div></dl><a className="text-link" href={`mailto:rationality@hilll.dev?subject=${encodeURIComponent(`Correction: ${event.title}`)}`}>Report a detail that needs updating ↗</a></div></article><aside className="detail-aside"><p className="eyebrow">PRACTICAL DETAILS</p><div className="detail-fact"><CalendarDays size={20}/><time dateTime={event.date}>{date}</time></div><div className="detail-fact"><Clock size={20}/><span>{event.time}<small>Munich local time · Europe/Berlin</small></span></div><div className="detail-fact"><MapPin size={20}/><span>{event.place}</span></div><div className="detail-fact"><Users size={20}/><span>{event.group}</span></div><a className="button primary" href={event.source} target="_blank" rel="noreferrer">Details & RSVP on {event.platform}<ArrowUpRight size={18}/></a><a className="button secondary" href={`${base}/downloads/${event.id}.ics`} download><Download size={17}/>Add this event to my calendar</a><p className="small-note">An .ics download adds this saved event only. It does not register you or receive later changes.</p>{event.extraSource&&<a className="text-link" href={event.extraSource} target="_blank" rel="noreferrer">Also announced on EA Forum ↗</a>}<p className="snapshot-note">Details saved 22 September 2026. Always check the original announcement.</p></aside></div></main><Footer/></>}
