'use client';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Mail, MessageCircle, CalendarDays } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { groups } from '@/lib/groups';
const questions=[
 ['Do I need to know about rationality or effective altruism?','EA Munich explicitly welcomes people without prior knowledge. The Estimation Game needs no special knowledge or preparation. Other events can be more focused: Philosophia’s discussions, for example, usually require reading a paper beforehand. Check the original announcement for your event.'],
 ['Can I come on my own?','Yes: EA Munich explicitly welcomes people coming alone. For any gathering, a short introduction to the host can help you find the group and feel more comfortable when you arrive. Each group organizes its own events.'],
 ['Are events in English or German?','Philosophia Munich holds its discussions in English. For the other groups, language depends on the event: check the announcement or ask the host. An English-language listing does not guarantee the language spoken at the gathering.'],
 ['What does it cost, and do I need to register?','Check the original announcement for registration, capacity, and any costs. Some gatherings take place in cafés or private homes, so the host may need to hear from you first. Food and drink arrangements also vary.'],
 ['What about accessibility or student eligibility?','Ask the organizer about step-free access, seating, noise, or other needs. For the AI Safety Munich Student Club, check its introduction or contact the club to confirm whether your situation fits its membership requirements.']
];
export function HomeSections(){return <>
 <section className="first-visit" id="first-visit"><div className="wrap first-grid"><div><p className="eyebrow">FIRST VISIT</p><h2>How a first visit<br/><em>usually works.</em></h2><p>You don’t need to know the difference between the groups, or anything about rationality, to turn up at one of their events.</p><a className="text-link" href="mailto:rationality@hilll.dev?subject=My%20first%20Munich%20meetup">Ask about your first visit <ArrowUpRight size={17}/></a></div><ol className="steps"><li><span>01</span><div><h3>Pick an event</h3><p>A dinner, a discussion or a game. The calendar lists them all.</p></div></li><li><span>02</span><div><h3>Get the practical details</h3><p>Check the original announcement for language, preparation, price, access, and registration.</p></div></li><li><span>03</span><div><h3>Say hello to the host</h3><p>A short message beforehand makes it easier to find the group when you arrive.</p></div></li></ol></div></section>
 <section className="section wrap" id="community"><div className="section-heading"><div><p className="eyebrow">THE GROUPS</p><h2>Five groups in Munich</h2></div><p className="heading-aside">Each has its own organisers,<br/>events and way of doing things.</p></div><div className="group-list">{groups.map(group=><article className="group-row" key={group.id}><div className="group-number">{group.number}<span>↗</span></div><div className="group-info"><p className="eyebrow">{group.topic}</p><h3>{group.name}</h3><p>{group.description}</p><div className="group-formats">{group.formats}</div></div><div className="group-actions"><a className="text-link" href={group.url} target="_blank" rel="noreferrer">{group.primary}<ArrowUpRight size={17}/></a>{group.links.length>0&&<details><summary>More ways to connect</summary><ul>{group.links.map(([label,url])=><li key={url}><a href={url} aria-label={`${label} — ${group.name}`} target={url.startsWith('mailto:')?undefined:'_blank'} rel="noreferrer">{label} ↗</a></li>)}</ul></details>}</div></article>)}</div><p className="section-note">The groups announce their own events; this page only collects them.</p></section>
 <section className="faq-section"><div className="wrap faq-grid"><div><p className="eyebrow">PRACTICAL QUESTIONS</p><h2>Before you<br/><em>come along.</em></h2><p>The details vary between groups.</p><MessageCircle size={40} strokeWidth={1.2}/></div><Accordion>{questions.map(([question,answer],i)=><AccordionItem key={question} value={`faq-${i}`}><AccordionTrigger className="faq-question">{question}</AccordionTrigger><AccordionContent className="faq-answer"><p>{answer}</p></AccordionContent></AccordionItem>)}</Accordion></div></section>
 <section className="wrap newsletter-section"><div className="newsletter-icon"><Mail size={30} strokeWidth={1.3}/></div><div><p className="eyebrow">MAILING LIST</p><h2>Event invites<br/><em>by email.</em></h2><p>Pick the topics you want to hear about. Change your preferences or unsubscribe whenever you like.</p><Link className="button primary" href="/subscribe">Get event invitations <ArrowUpRight size={18}/></Link><Link className="text-link" href="/sample-email">See an example <ArrowRight size={17}/></Link></div><div className="newsletter-note"><CalendarDays size={25}/><p>THREE TOPICS.<br/>PICK YOURS.</p><span>The live mailing list promises no open or click tracking. Unsubscribe at any time.</span></div></section>
 </>}
